/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadora1;

/**
 *
 * @author pjdiaz
 */
public class Calculadora1 extends javax.swing.JFrame {

    int num1, num2; //Variables para almacenar los valores ingresador 
    String signo; // Signo se refiere a la operacion a desarrollar para los valores ingresados

    /**
     * Creates new form Calculadora
     */
    public Calculadora1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pantalla = new javax.swing.JLabel();
        ButtonC = new javax.swing.JButton();
        ButtonDiv = new javax.swing.JButton();
        ButtonMult = new javax.swing.JButton();
        ButtonRest = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        ButtonSum = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        ButtonPoint = new javax.swing.JButton();
        ButtonEqual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font(".AppleSystemUIFont", 2, 14)); // NOI18N
        setLocation(new java.awt.Point(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pantalla.setForeground(new java.awt.Color(0, 0, 0));
        Pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Pantalla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Pantalla.setName("Pantalla"); // NOI18N
        Pantalla.setOpaque(true);
        getContentPane().add(Pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 17, 222, 62));

        ButtonC.setText("C");
        ButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonC, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 85, 51, 44));

        ButtonDiv.setText("/");
        ButtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDivActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 85, 51, 44));

        ButtonMult.setText("*");
        ButtonMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMultActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonMult, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 85, 51, 44));

        ButtonRest.setText("-");
        ButtonRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRestActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 85, 51, 44));

        Button7.setText("7");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });
        getContentPane().add(Button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 135, 51, 44));

        Button8.setText("8");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });
        getContentPane().add(Button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 135, 51, 44));

        Button9.setText("9");
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });
        getContentPane().add(Button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 135, 51, 44));

        Button4.setText("4");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });
        getContentPane().add(Button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 185, 51, 44));

        Button5.setText("5");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });
        getContentPane().add(Button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 185, 51, 44));

        Button6.setText("6");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });
        getContentPane().add(Button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 185, 51, 44));

        ButtonSum.setText("+");
        ButtonSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSumActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 135, 51, 94));

        Button1.setText("1");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        getContentPane().add(Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 235, 51, 44));

        Button2.setText("2");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });
        getContentPane().add(Button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 235, 51, 44));

        Button3.setText("3");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });
        getContentPane().add(Button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 235, 51, 44));

        Button0.setText("0");
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });
        getContentPane().add(Button0, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 285, 108, 44));

        ButtonPoint.setText(".");
        getContentPane().add(ButtonPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 285, 51, 44));

        ButtonEqual.setText("=");
        ButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEqualActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 235, 51, 94));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCActionPerformed
        this.Pantalla.setText("");
    }//GEN-LAST:event_ButtonCActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        this.Pantalla.setText(this.Pantalla.getText() + "9");
    }//GEN-LAST:event_Button9ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        this.Pantalla.setText(this.Pantalla.getText() + "5");
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        this.Pantalla.setText(this.Pantalla.getText() + "3");
    }//GEN-LAST:event_Button3ActionPerformed

    private void ButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEqualActionPerformed
        num2 = Integer.parseInt(Pantalla.getText());

        switch (signo) {//switch para selecion de operacion a utilizar 
            case "+":
                Pantalla.setText(Integer.toString(num1 + num2));
                break;
            case "*":
                Pantalla.setText(Integer.toString(num1 * num2));
                break;

            case "-":
                Pantalla.setText(Integer.toString(num1 - num2));
                break;

            case "/":
                Pantalla.setText(Integer.toString(num1 / num2));
                break;

        }
    }//GEN-LAST:event_ButtonEqualActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        this.Pantalla.setText(this.Pantalla.getText() + "0");
    }//GEN-LAST:event_Button0ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        this.Pantalla.setText(this.Pantalla.getText() + "7");
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        this.Pantalla.setText(this.Pantalla.getText() + "1");
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        this.Pantalla.setText(this.Pantalla.getText() + "2");
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        this.Pantalla.setText(this.Pantalla.getText() + "4");
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        this.Pantalla.setText(this.Pantalla.getText() + "6");
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        this.Pantalla.setText(this.Pantalla.getText() + "8");
    }//GEN-LAST:event_Button8ActionPerformed

    //Se almacena valor ingresdo en el Jlabel "Pantalla y se almacena en la variable nun1 al dar click en la operacion a realizar y se limpia pantalla, se ingresa el segundo valor y al dar igual se alamacena en la variable num2 y se realiza la operacion. 
    private void ButtonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDivActionPerformed
        num1 = Integer.parseInt(Pantalla.getText());
        signo = "/";
        Pantalla.setText("");
    }//GEN-LAST:event_ButtonDivActionPerformed

    private void ButtonMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMultActionPerformed
        num1 = Integer.parseInt(Pantalla.getText());
        signo = "*";
        Pantalla.setText("");
    }//GEN-LAST:event_ButtonMultActionPerformed

    private void ButtonRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRestActionPerformed
        num1 = Integer.parseInt(Pantalla.getText());
        signo = "-";
        Pantalla.setText("");
    }//GEN-LAST:event_ButtonRestActionPerformed

    private void ButtonSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSumActionPerformed
        num1 = Integer.parseInt(Pantalla.getText());
        signo = "+";
        Pantalla.setText("");
    }//GEN-LAST:event_ButtonSumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonC;
    private javax.swing.JButton ButtonDiv;
    private javax.swing.JButton ButtonEqual;
    private javax.swing.JButton ButtonMult;
    private javax.swing.JButton ButtonPoint;
    private javax.swing.JButton ButtonRest;
    private javax.swing.JButton ButtonSum;
    private javax.swing.JLabel Pantalla;
    // End of variables declaration//GEN-END:variables
}
